"""init

Revision ID: 48018865a591
Revises: 
Create Date: 2026-07-27 12:40:23.031355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48018865a591'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=1000), nullable=True),
    sa.Column('address', sa.String(length=1000), nullable=True),
    sa.Column('phone', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('working_hours', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_extra', sa.JSON(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_company_source')
    )
    op.create_index(op.f('ix_companies_source'), 'companies', ['source'], unique=False)
    op.create_index(op.f('ix_companies_source_id'), 'companies', ['source_id'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('records_found', sa.Integer(), nullable=False),
    sa.Column('records_upserted', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_runs_source'), 'scrape_runs', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrape_runs_source'), table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_index(op.f('ix_companies_source_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_source'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
