"""add scrape_runs.records_failed

Revision ID: 7e7dcff54acd
Revises: 69e518ab04f2
Create Date: 2026-08-13 07:34:09.912265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e7dcff54acd'
down_revision: Union[str, None] = '69e518ab04f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_runs', sa.Column('records_failed', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scrape_runs', 'records_failed')
    # ### end Alembic commands ###
