"""add permission_request resolution_note

Revision ID: c2787e18090b
Revises: 43be409cc3f9
Create Date: 2026-07-29 10:55:47.496962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2787e18090b'
down_revision: Union[str, None] = '43be409cc3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission_requests', sa.Column('resolution_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permission_requests', 'resolution_note')
    # ### end Alembic commands ###
