"""add rubric_progress for resumable crawls

Revision ID: cf4ebe0689c1
Revises: e35d1483b0ae
Create Date: 2026-08-20 12:12:10.287333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4ebe0689c1'
down_revision: Union[str, None] = 'e35d1483b0ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rubric_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('rubric_key', sa.String(length=512), nullable=False),
    sa.Column('companies_seen', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'rubric_key', name='uq_rubric_progress')
    )
    op.create_index(op.f('ix_rubric_progress_rubric_key'), 'rubric_progress', ['rubric_key'], unique=False)
    op.create_index(op.f('ix_rubric_progress_source'), 'rubric_progress', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rubric_progress_source'), table_name='rubric_progress')
    op.drop_index(op.f('ix_rubric_progress_rubric_key'), table_name='rubric_progress')
    op.drop_table('rubric_progress')
    # ### end Alembic commands ###
